import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sidebar/sidebar";
import Navbar from "@/components/navbar/navbar";
import "@radix-ui/themes/styles.css";
import RightBar from "@/components/rightsidebar/rightsidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full bg-[#0e1113] flex justify-center items-center ">
        {children}
      </body>
    </html>
  );
}
